os: linux
dist: focal
arch: arm64-graviton2
language: node_js
node_js:
  - 16
  - 12
install:
  - npm install --legacy-peer-deps
script:
  - npm run test
after_success:
  - semantic-release
notifications:
  email: false
cache:
  npm: false
